Repository School-of-Company/Gwangsan-Server, pull requests merged in 2025-07, with the labels that each got.

#37 엔티티 수정
  src/main/java/team/startup/gwangsan/domain/dong/entity/Dong.java
  src/main/java/team/startup/gwangsan/domain/post/entity/TradeComplete.java
Labels: 0️⃣ Priority: Critical

#39 admin 도메인 API 개발
  src/main/java/team/startup/gwangsan/domain/admin/entity/AdminAlert.java
  src/main/java/team/startup/gwangsan/domain/admin/entity/constant/AlertType.java
  src/main/java/team/startup/gwangsan/domain/admin/exception/NotFoundAlertTypeException.java
  src/main/java/team/startup/gwangsan/domain/admin/exception/NotFoundPendingMemberException.java
  src/main/java/team/startup/gwangsan/domain/admin/presentation/AdminController.java
  src/main/java/team/startup/gwangsan/domain/admin/presentation/dto/request/AdminSignInRequest.java
  src/main/java/team/startup/gwangsan/domain/admin/presentation/dto/request/UpdateMemberRoleRequest.java
  src/main/java/team/startup/gwangsan/domain/admin/presentation/dto/request/UpdateMemberStatusRequest.java
  src/main/java/team/startup/gwangsan/domain/admin/presentation/dto/response/GetAdminAlertResponse.java
  src/main/java/team/startup/gwangsan/domain/admin/presentation/dto/response/GetReportAlertResponse.java
  src/main/java/team/startup/gwangsan/domain/admin/presentation/dto/response/GetSignUpAlertResponse.java
  src/main/java/team/startup/gwangsan/domain/admin/repository/AdminAlertRepository.java
  src/main/java/team/startup/gwangsan/domain/admin/repository/custom/AdminAlertCustomRepository.java
  src/main/java/team/startup/gwangsan/domain/admin/repository/custom/impl/AdminAlertCustomRepositoryImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/service/CreateAdminAlertService.java
  src/main/java/team/startup/gwangsan/domain/admin/service/FindAlertByAlertTypeAndPlaceService.java
  src/main/java/team/startup/gwangsan/domain/admin/service/SignInAdminService.java
  src/main/java/team/startup/gwangsan/domain/admin/service/UpdateMemberRoleService.java
  src/main/java/team/startup/gwangsan/domain/admin/service/UpdateMemberStatusService.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/CreateAdminAlertServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/FindAlertByAlertTypeAndPlaceServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/SignInAdminServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/UpdateMemberRoleServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/UpdateMemberStatusServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/util/ValidatePlaceUtil.java
  src/main/java/team/startup/gwangsan/domain/member/entity/Member.java
  src/main/java/team/startup/gwangsan/domain/member/repository/MemberRepository.java
  src/main/java/team/startup/gwangsan/domain/member/repository/custom/MemberCustomRepository.java
  src/main/java/team/startup/gwangsan/domain/member/repository/custom/impl/MemberCustomRepositoryImpl.java
  src/main/java/team/startup/gwangsan/domain/report/exception/NotFoundReportException.java
  src/main/java/team/startup/gwangsan/domain/report/presentation/dto/response/GetReportResponse.java
  src/main/java/team/startup/gwangsan/domain/report/repository/ReportImageRepository.java
  src/main/java/team/startup/gwangsan/domain/report/repository/ReportRepository.java
  src/main/java/team/startup/gwangsan/domain/report/repository/custom/ReportCustomRepository.java
  src/main/java/team/startup/gwangsan/domain/report/repository/custom/impl/ReportCustomRepositoryImpl.java
  src/main/java/team/startup/gwangsan/global/event/CreateAdminAlertEvent.java
  src/main/java/team/startup/gwangsan/global/event/handler/CreateAdminAlertEventListener.java
  src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
  src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
Labels: 1️⃣ Priority: High

#51 `FCM` 푸시 알림 구현
  .gitignore
  build.gradle
  src/main/java/team/startup/gwangsan/domain/notification/NotificationPort.java
  src/main/java/team/startup/gwangsan/domain/notification/entity/constant/NotificationType.java
  src/main/java/team/startup/gwangsan/domain/notification/service/SendNotificationService.java
  src/main/java/team/startup/gwangsan/domain/notification/service/impl/SendNotificationServiceImpl.java
  src/main/java/team/startup/gwangsan/global/event/SendNotificationEvent.java
  src/main/java/team/startup/gwangsan/global/event/handler/SendNotificationEventListener.java
  src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
  src/main/java/team/startup/gwangsan/global/thirdparty/firebase/FcmAdapter.java
  src/main/java/team/startup/gwangsan/global/thirdparty/firebase/config/FirebaseConfig.java
  src/main/java/team/startup/gwangsan/global/thirdparty/firebase/exception/FirebaseInitializationException.java
Labels: 1️⃣ Priority: High, ✨ Feature

#54 엔티티 수정
  src/main/java/team/startup/gwangsan/domain/chat/entity/ChatMessage.java
  src/main/java/team/startup/gwangsan/domain/chat/entity/ChatMessageImage.java
  src/main/java/team/startup/gwangsan/domain/chat/entity/constant/MessageType.java
  src/main/java/team/startup/gwangsan/domain/image/entity/Image.java
  src/main/java/team/startup/gwangsan/domain/member/entity/MemberDetail.java
  src/main/java/team/startup/gwangsan/domain/notice/entity/Notice.java
Labels: 0️⃣ Priority: Critical

#60 admin alert 조회 로직 수정
  src/main/java/team/startup/gwangsan/domain/admin/repository/custom/AdminAlertCustomRepository.java
  src/main/java/team/startup/gwangsan/domain/admin/repository/custom/impl/AdminAlertCustomRepositoryImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/FindAlertByAlertTypeAndPlaceServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/member/repository/custom/MemberCustomRepository.java
  src/main/java/team/startup/gwangsan/domain/member/repository/custom/impl/MemberCustomRepositoryImpl.java
  src/main/java/team/startup/gwangsan/domain/notice/service/impl/FindAllNoticeServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/place/repository/PlaceRepository.java
  src/main/java/team/startup/gwangsan/domain/report/repository/custom/ReportCustomRepository.java
  src/main/java/team/startup/gwangsan/domain/report/repository/custom/impl/ReportCustomRepositoryImpl.java
Labels: 1️⃣ Priority: High

#63 비밀번호 검증 메서드 주석 해제
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/SignInAdminServiceImpl.java
Labels: 0️⃣ Priority: Critical

#67 CORS 문제 해결
  .env.example
  src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
  src/main/java/team/startup/gwangsan/global/security/config/WebMvcConfig.java
  src/main/resources/application.yml
Labels: 1️⃣ Priority: High

#83 admin alert 조회 응답에 placeName 추가
  src/main/java/team/startup/gwangsan/domain/admin/presentation/dto/response/GetReportAlertResponse.java
  src/main/java/team/startup/gwangsan/domain/admin/presentation/dto/response/GetSignUpAlertResponse.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/FindAlertByAlertTypeAndPlaceServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/member/repository/custom/MemberDetailCustomRepository.java
  src/main/java/team/startup/gwangsan/domain/member/repository/custom/impl/MemberCustomRepositoryImpl.java
  src/main/java/team/startup/gwangsan/domain/member/repository/custom/impl/MemberDetailCustomRepositoryImpl.java
  src/main/java/team/startup/gwangsan/domain/report/repository/custom/impl/ReportCustomRepositoryImpl.java
Labels: 1️⃣ Priority: High

#87 오류 수정
  src/main/java/team/startup/gwangsan/domain/auth/service/impl/SignUpServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/member/entity/MemberDetail.java
  src/main/java/team/startup/gwangsan/domain/member/peresentation/dto/request/UpdateMyInfoRequest.java
  src/main/java/team/startup/gwangsan/domain/member/peresentation/dto/response/FindAllUserInfoResponse.java
  src/main/java/team/startup/gwangsan/domain/member/peresentation/dto/response/FindMyInfoResponse.java
  src/main/java/team/startup/gwangsan/domain/member/peresentation/dto/response/FindUserInfoResponse.java
  src/main/java/team/startup/gwangsan/domain/member/service/impl/FindAllUserInfoServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/member/service/impl/FindMyInfoServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/member/service/impl/FindUserInfoServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/member/service/impl/UpdateMyInfoServiceImpl.java
  src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
Labels: 0️⃣ Priority: Critical

#92 신고 기능 개발
  src/main/java/team/startup/gwangsan/domain/report/exception/AlreadyReportedException.java
  src/main/java/team/startup/gwangsan/domain/report/exception/SelfReportNotAllowedException.java
  src/main/java/team/startup/gwangsan/domain/report/presentation/ReportController.java
  src/main/java/team/startup/gwangsan/domain/report/presentation/dto/request/CreateProductReportRequest.java
  src/main/java/team/startup/gwangsan/domain/report/repository/ReportRepository.java
  src/main/java/team/startup/gwangsan/domain/report/service/CreateProductReportService.java
  src/main/java/team/startup/gwangsan/domain/report/service/impl/CreateProductReportServiceImpl.java
  src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
  src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
Labels: 1️⃣ Priority: High, ✨ Feature

#93 거래 완료 api 추가
  src/main/java/team/startup/gwangsan/domain/admin/entity/AdminAlert.java
  src/main/java/team/startup/gwangsan/domain/admin/entity/constant/AlertType.java
  src/main/java/team/startup/gwangsan/domain/admin/exception/NotFoundAdminAlertException.java
  src/main/java/team/startup/gwangsan/domain/admin/presentation/AdminController.java
  src/main/java/team/startup/gwangsan/domain/admin/presentation/dto/response/GetAdminAlertResponse.java
  src/main/java/team/startup/gwangsan/domain/admin/presentation/dto/response/GetTradeCompleteAlertResponse.java
  src/main/java/team/startup/gwangsan/domain/admin/repository/AdminAlertRepository.java
  src/main/java/team/startup/gwangsan/domain/admin/repository/custom/impl/AdminAlertCustomRepositoryImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/service/CompleteTradeService.java
  src/main/java/team/startup/gwangsan/domain/admin/service/CreateTradeCompleteAlertService.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/CompleteTradeServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/CreateAdminAlertServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/CreateTradeCompleteAlertServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/FindAlertByAlertTypeAndPlaceServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/UpdateMemberRoleServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/UpdateMemberStatusServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/util/ValidatePlaceUtil.java
  src/main/java/team/startup/gwangsan/domain/chat/entity/ChatMessage.java
  src/main/java/team/startup/gwangsan/domain/chat/repository/ChatMessageRepository.java
  src/main/java/team/startup/gwangsan/domain/member/entity/MemberDetail.java
  src/main/java/team/startup/gwangsan/domain/notification/entity/constant/NotificationType.java
  src/main/java/team/startup/gwangsan/domain/notification/repository/DeviceTokenRepository.java
  src/main/java/team/startup/gwangsan/domain/notification/service/impl/SendNotificationServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/post/entity/Product.java
  src/main/java/team/startup/gwangsan/domain/post/entity/TradeComplete.java
  src/main/java/team/startup/gwangsan/domain/post/exception/CannotCompleteTradeException.java
  src/main/java/team/startup/gwangsan/domain/post/exception/CannotSelectSelfException.java
  src/main/java/team/startup/gwangsan/domain/post/presentation/PostController.java
  src/main/java/team/startup/gwangsan/domain/post/presentation/dto/request/RequestTradeCompleteRequest.java
  src/main/java/team/startup/gwangsan/domain/post/repository/TradeCompleteRepository.java
  src/main/java/team/startup/gwangsan/domain/post/repository/custom/TradeCompleteCustomRepository.java
  src/main/java/team/startup/gwangsan/domain/post/repository/custom/impl/TradeCompleteCustomRepositoryImpl.java
  src/main/java/team/startup/gwangsan/domain/post/service/RequestTradeCompleteService.java
  src/main/java/team/startup/gwangsan/domain/post/service/impl/FindProductByCurrentUserAndTypeAndModeServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/post/service/impl/FindProductsByMemberIdServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/post/service/impl/RequestTradeCompleteServiceImpl.java
  src/main/java/team/startup/gwangsan/global/event/CreateAdminAlertEvent.java
  src/main/java/team/startup/gwangsan/global/event/handler/CreateAdminAlertEventListener.java
  src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
Labels: 1️⃣ Priority: High

#106 엑세스 토큰 만료일 수정
  src/main/java/team/startup/gwangsan/global/security/jwt/JwtProvider.java
Labels: 1️⃣ Priority: High

#112 회원가입 시 어드민 알림 이벤트 호출 코드 추가
  src/main/java/team/startup/gwangsan/domain/auth/service/impl/SignUpServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/post/service/impl/RequestTradeCompleteServiceImpl.java
Labels: 1️⃣ Priority: High

#113 리뷰 조회 수정
  src/main/java/team/startup/gwangsan/domain/post/repository/ProductImageRepository.java
  src/main/java/team/startup/gwangsan/domain/review/presentation/ReviewController.java
  src/main/java/team/startup/gwangsan/domain/review/presentation/dto/response/ReviewResponse.java
  src/main/java/team/startup/gwangsan/domain/review/repository/ReviewRepository.java
  src/main/java/team/startup/gwangsan/domain/review/service/GetMyReviewListService.java
  src/main/java/team/startup/gwangsan/domain/review/service/impl/CreateReviewServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/review/service/impl/GetMyReviewListServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/review/service/impl/GetReceivedReviewListServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/review/service/impl/GetReviewByMemberServiceImpl.java
Labels: 0️⃣ Priority: Critical

#115 어드민 알림 조회 시 product 관련 오류 수정
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/FindAlertByAlertTypeAndPlaceServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/post/service/FindProductByIdService.java
  src/main/java/team/startup/gwangsan/domain/post/service/impl/FindProductByIdServiceImpl.java
Labels: 0️⃣ Priority: Critical

#124 요청 파일 크기 제한 수정
  src/main/resources/application.yml
Labels: 0️⃣ Priority: Critical

#135 앱 알림 api 추가
  src/main/java/team/startup/gwangsan/domain/admin/service/CreateAdminAlertService.java
  src/main/java/team/startup/gwangsan/domain/admin/service/CreateTradeCompleteAlertService.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/CompleteTradeServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/CreateAdminAlertServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/CreateTradeCompleteAlertServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/alert/entity/Alert.java
  src/main/java/team/startup/gwangsan/domain/alert/entity/constant/AlertType.java
  src/main/java/team/startup/gwangsan/domain/alert/presentation/AlertController.java
  src/main/java/team/startup/gwangsan/domain/alert/presentation/dto/response/GetAlertResponse.java
  src/main/java/team/startup/gwangsan/domain/alert/repository/AlertRepository.java
  src/main/java/team/startup/gwangsan/domain/alert/service/CreateAlertMembersService.java
  src/main/java/team/startup/gwangsan/domain/alert/service/CreateAlertService.java
  src/main/java/team/startup/gwangsan/domain/alert/service/FindAlertByCurrentService.java
  src/main/java/team/startup/gwangsan/domain/alert/service/impl/CreateAlertMembersServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/alert/service/impl/CreateAlertServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/alert/service/impl/FindAlertByCurrentServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/auth/service/impl/SignUpServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/member/repository/MemberRepository.java
  src/main/java/team/startup/gwangsan/domain/member/repository/custom/MemberDetailCustomRepository.java
  src/main/java/team/startup/gwangsan/domain/member/repository/custom/impl/MemberDetailCustomRepositoryImpl.java
  src/main/java/team/startup/gwangsan/domain/notice/service/impl/CreateNoticeServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/post/exception/NotFoundTradeCompleteException.java
  src/main/java/team/startup/gwangsan/domain/post/repository/ProductRepository.java
  src/main/java/team/startup/gwangsan/domain/post/service/impl/RequestTradeCompleteServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/report/service/impl/CreateProductReportServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/review/exception/NotFoundReviewException.java
  src/main/java/team/startup/gwangsan/domain/review/service/impl/CreateReviewServiceImpl.java
  src/main/java/team/startup/gwangsan/global/event/CreateAdminAlertEvent.java
  src/main/java/team/startup/gwangsan/global/event/CreateAlertEvent.java
  src/main/java/team/startup/gwangsan/global/event/CreateAlertMembersEvent.java
  src/main/java/team/startup/gwangsan/global/event/handler/CreateAdminAlertEventListener.java
  src/main/java/team/startup/gwangsan/global/event/handler/CreateAlertEventListener.java
  src/main/java/team/startup/gwangsan/global/event/handler/CreateAlertMembersEventListener.java
  src/main/java/team/startup/gwangsan/global/event/handler/SendNotificationEventListener.java
  src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
Labels: 0️⃣ Priority: Critical

#138 채팅 검증 주석 처리
  src/main/java/team/startup/gwangsan/domain/post/service/impl/RequestTradeCompleteServiceImpl.java
Labels: 0️⃣ Priority: Critical

#139 nullPointerException 해결
  src/main/java/team/startup/gwangsan/domain/notice/service/impl/CreateNoticeServiceImpl.java
Labels: 0️⃣ Priority: Critical

#144 앱 알림 조회 응답에 sourceId 필드 추가
  src/main/java/team/startup/gwangsan/domain/alert/presentation/dto/response/GetAlertResponse.java
  src/main/java/team/startup/gwangsan/domain/alert/service/impl/FindAlertByCurrentServiceImpl.java
Labels: 1️⃣ Priority: High

#151 어드민 알림 삭제 api 추가
  src/main/java/team/startup/gwangsan/domain/admin/presentation/AdminController.java
  src/main/java/team/startup/gwangsan/domain/admin/service/DeleteAdminAlertService.java
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/DeleteAdminAlertServiceImpl.java
Labels: 1️⃣ Priority: High

#149 앱 알림 조회 시 잘못된 sourceId 수정
  src/main/java/team/startup/gwangsan/domain/alert/service/impl/CreateAlertServiceImpl.java
Labels: 1️⃣ Priority: High

#157 전체 멤버 정보 조회 수정
  src/main/java/team/startup/gwangsan/domain/member/repository/MemberDetailRepository.java
  src/main/java/team/startup/gwangsan/domain/member/repository/custom/MemberDetailCustomRepository.java
  src/main/java/team/startup/gwangsan/domain/member/repository/custom/impl/MemberDetailCustomRepositoryImpl.java
  src/main/java/team/startup/gwangsan/domain/member/service/impl/FindAllUserInfoServiceImpl.java
Labels: 1️⃣ Priority: High

#159 회원가입 수락 시 5000광산 지급 로직 추가
  src/main/java/team/startup/gwangsan/domain/admin/service/impl/VerificationSignUpServiceImpl.java
Labels: 1️⃣ Priority: High

#161 앱 알림 읽음 관련 api 추가
  src/main/java/team/startup/gwangsan/domain/alert/entity/Alert.java
  src/main/java/team/startup/gwangsan/domain/alert/presentation/AlertController.java
  src/main/java/team/startup/gwangsan/domain/alert/presentation/dto/response/ExistsAlertResponse.java
  src/main/java/team/startup/gwangsan/domain/alert/repository/AlertRepository.java
  src/main/java/team/startup/gwangsan/domain/alert/repository/custom/AlertCustomRepository.java
  src/main/java/team/startup/gwangsan/domain/alert/repository/custom/impl/AlertCustomRepositoryImpl.java
  src/main/java/team/startup/gwangsan/domain/alert/service/ExistsUnreadAlertService.java
  src/main/java/team/startup/gwangsan/domain/alert/service/ReadAlertService.java
  src/main/java/team/startup/gwangsan/domain/alert/service/impl/CreateAlertMembersServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/alert/service/impl/CreateAlertServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/alert/service/impl/ExistsUnreadAlertServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/alert/service/impl/ReadAlertServiceImpl.java
Labels: 2️⃣ Priority: Medium

#163 공지 조회 관련 수정
  src/main/java/team/startup/gwangsan/domain/notice/presentation/NoticeController.java
  src/main/java/team/startup/gwangsan/domain/notice/presentation/dto/request/CreateNoticeRequest.java
  src/main/java/team/startup/gwangsan/domain/notice/presentation/dto/request/UpdateNoticeRequest.java
  src/main/java/team/startup/gwangsan/domain/notice/repository/NoticeRepository.java
  src/main/java/team/startup/gwangsan/domain/notice/service/CreateNoticeService.java
  src/main/java/team/startup/gwangsan/domain/notice/service/UpdateNoticeService.java
  src/main/java/team/startup/gwangsan/domain/notice/service/impl/CreateNoticeServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/notice/service/impl/FindAllNoticeServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/notice/service/impl/FindNoticeServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/notice/service/impl/UpdateNoticeServiceImpl.java
Labels: 1️⃣ Priority: High

#165 공지 수정, 삭제 수정
  src/main/java/team/startup/gwangsan/domain/notice/exception/UnauthorizedNoticeAccessException.java
  src/main/java/team/startup/gwangsan/domain/notice/repository/NoticeImageRepository.java
  src/main/java/team/startup/gwangsan/domain/notice/service/impl/DeleteNoticeServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/notice/service/impl/UpdateNoticeServiceImpl.java
  src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
Labels: 2️⃣ Priority: Medium
