Repository School-of-Company/Gwangsan-Server, pull requests merged in 2025-06, with the labels that each got.

#2 프로젝트 세팅
  build.gradle
Labels: ⚙ Setting

#5 엔티티 생성
  .gitignore
  src/main/java/team/startup/gwangsan/GwangsanApplication.java
  src/main/java/team/startup/gwangsan/domain/chat/entity/ChatMessage.java
  src/main/java/team/startup/gwangsan/domain/chat/entity/ChatRoom.java
  src/main/java/team/startup/gwangsan/domain/dong/entity/Dong.java
  src/main/java/team/startup/gwangsan/domain/member/entity/Member.java
  src/main/java/team/startup/gwangsan/domain/member/entity/MemberDetail.java
  src/main/java/team/startup/gwangsan/domain/member/entity/constant/MemberRole.java
  src/main/java/team/startup/gwangsan/domain/member/entity/constant/MemberStatus.java
  src/main/java/team/startup/gwangsan/domain/notice/entity/Notice.java
  src/main/java/team/startup/gwangsan/domain/notice/entity/NoticeImage.java
  src/main/java/team/startup/gwangsan/domain/place/entity/Head.java
  src/main/java/team/startup/gwangsan/domain/place/entity/Place.java
  src/main/java/team/startup/gwangsan/domain/post/entity/Product.java
  src/main/java/team/startup/gwangsan/domain/post/entity/ProductImage.java
  src/main/java/team/startup/gwangsan/domain/post/entity/constant/Mode.java
  src/main/java/team/startup/gwangsan/domain/post/entity/constant/ProductStatus.java
  src/main/java/team/startup/gwangsan/domain/post/entity/constant/Type.java
  src/main/java/team/startup/gwangsan/domain/relatedkeyword/entity/MemberRelatedKeyword.java
  src/main/java/team/startup/gwangsan/domain/relatedkeyword/entity/RelatedKeyword.java
  src/main/java/team/startup/gwangsan/domain/report/entity/Report.java
  src/main/java/team/startup/gwangsan/domain/review/entity/Review.java
  src/main/java/team/startup/gwangsan/domain/suspend/entity/Suspend.java
Labels: ⚙ Setting

#11 중간 테이블 엔티티 추가
  src/main/java/team/startup/gwangsan/domain/notice/entity/Notice.java
  src/main/java/team/startup/gwangsan/domain/notice/entity/NoticeImage.java
  src/main/java/team/startup/gwangsan/domain/post/entity/Product.java
  src/main/java/team/startup/gwangsan/domain/post/entity/ProductImage.java
Labels: 1️⃣ Priority: High

#13 시큐리티 기본 세팅
  build.gradle
  compose.yaml
  src/main/java/team/startup/gwangsan/GwangsanApplication.java
  src/main/java/team/startup/gwangsan/domain/member/exception/NotFoundMemberException.java
  src/main/java/team/startup/gwangsan/domain/member/repository/MemberRepository.java
  src/main/java/team/startup/gwangsan/global/auth/MemberDetails.java
  src/main/java/team/startup/gwangsan/global/auth/MemberDetailsService.java
  src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
  src/main/java/team/startup/gwangsan/global/exception/ErrorResponse.java
  src/main/java/team/startup/gwangsan/global/exception/GlobalException.java
  src/main/java/team/startup/gwangsan/global/exception/GlobalExceptionHandler.java
  src/main/java/team/startup/gwangsan/global/filter/ExceptionFilter.java
  src/main/java/team/startup/gwangsan/global/filter/JwtAuthenticationFilter.java
  src/main/java/team/startup/gwangsan/global/filter/JwtFilter.java
  src/main/java/team/startup/gwangsan/global/filter/RequestLogFilter.java
  src/main/java/team/startup/gwangsan/global/security/config/JwtSecurityConfig.java
  src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
  src/main/java/team/startup/gwangsan/global/security/exception/ExpiredTokenException.java
  src/main/java/team/startup/gwangsan/global/security/exception/InvalidMemberPrincipalException.java
  src/main/java/team/startup/gwangsan/global/security/exception/InvalidTokenException.java
  src/main/java/team/startup/gwangsan/global/security/handler/JwtAccessDeniedHandler.java
  src/main/java/team/startup/gwangsan/global/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/team/startup/gwangsan/global/security/jwt/JwtProperties.java
  src/main/java/team/startup/gwangsan/global/security/jwt/JwtProvider.java
  src/main/java/team/startup/gwangsan/global/security/jwt/TokenParser.java
  src/main/java/team/startup/gwangsan/global/util/MemberUtil.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ⚙ Setting, ✨ Feature

#17 이미지 업로드, 삭제 API 추가
  .env.example
  build.gradle
  src/main/java/team/startup/gwangsan/domain/image/exception/ImageNotFoundException.java
  src/main/java/team/startup/gwangsan/domain/image/exception/ImageUploadFailedException.java
  src/main/java/team/startup/gwangsan/domain/image/exception/NotFoundImageIdsException.java
  src/main/java/team/startup/gwangsan/domain/image/presentation/ImageController.java
  src/main/java/team/startup/gwangsan/domain/image/presentation/dto/request/UploadImageRequest.java
  src/main/java/team/startup/gwangsan/domain/image/presentation/dto/response/UploadImageResponse.java
  src/main/java/team/startup/gwangsan/domain/image/repository/ImageRepository.java
  src/main/java/team/startup/gwangsan/domain/image/service/DeleteImageService.java
  src/main/java/team/startup/gwangsan/domain/image/service/UploadImageService.java
  src/main/java/team/startup/gwangsan/domain/image/service/impl/DeleteImageServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/image/service/impl/UploadImageServiceImpl.java
  src/main/java/team/startup/gwangsan/domain/notice/repository/NoticeImageRepository.java
  src/main/java/team/startup/gwangsan/domain/post/repository/ProductImageRepository.java
  src/main/java/team/startup/gwangsan/domain/report/repository/ReportImageRepository.java
  src/main/java/team/startup/gwangsan/global/config/AsyncConfig.java
  src/main/java/team/startup/gwangsan/global/event/DeleteNotUsedImageEvent.java
  src/main/java/team/startup/gwangsan/global/event/constant/ImageType.java
  src/main/java/team/startup/gwangsan/global/event/handler/DeleteNotUsedImageEventListener.java
  src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
  src/main/java/team/startup/gwangsan/global/thirdparty/aws/s3/config/S3Config.java
  src/main/java/team/startup/gwangsan/global/thirdparty/aws/s3/service/S3DeleteService.java
  src/main/java/team/startup/gwangsan/global/thirdparty/aws/s3/service/S3UploadService.java
  src/main/java/team/startup/gwangsan/global/util/ImageValidateUtil.java
  src/main/resources/application.yml
Labels: 3️⃣ Priority: Low, ✨ Feature

#20 수정된 ddl에 따라 엔티티 수정
  src/main/java/team/startup/gwangsan/domain/chat/entity/ChatMessage.java
  src/main/java/team/startup/gwangsan/domain/chat/entity/ChatRoom.java
  src/main/java/team/startup/gwangsan/domain/notice/entity/Notice.java
  src/main/java/team/startup/gwangsan/domain/report/entity/Report.java
  src/main/java/team/startup/gwangsan/domain/review/entity/Review.java
Labels: 1️⃣ Priority: High, ⚡️ Simple

#22 회원가입 sms 인증번호 전송
  build.gradle
  src/main/java/team/startup/gwangsan/domain/sms/entity/SmsAuthEntity.java
  src/main/java/team/startup/gwangsan/domain/sms/exception/AuthCodeGenerationException.java
  src/main/java/team/startup/gwangsan/domain/sms/exception/TooManyRequestAuthCodeException.java
  src/main/java/team/startup/gwangsan/domain/sms/presentation/SmsController.java
  src/main/java/team/startup/gwangsan/domain/sms/presentation/dto/SendSmsRequest.java
  src/main/java/team/startup/gwangsan/domain/sms/service/SendSmsService.java
  src/main/java/team/startup/gwangsan/domain/sms/service/impl/SendSmsServiceImpl.java
  src/main/java/team/startup/gwangsan/global/exception/ErrorCode.java
  src/main/java/team/startup/gwangsan/global/security/config/SecurityConfig.java
  src/main/java/team/startup/gwangsan/global/sms/SmsConfig.java
  src/main/java/team/startup/gwangsan/global/sms/SmsProperties.java
  src/main/resources/application.yml
Labels: 1️⃣ Priority: High, ✨ Feature

#25 report 엔티티의 title 필드 삭제 및 reportType 필드 추가
  src/main/java/team/startup/gwangsan/domain/admin/entity/AdminAlert.java
  src/main/java/team/startup/gwangsan/domain/report/entity/Report.java
  src/main/java/team/startup/gwangsan/domain/report/entity/constant/ReportType.java
Labels: 1️⃣ Priority: High
